# dbt_project.yml
name: 'atl_analytics'
version: '1.0.0'
config-version: 2

# Project-level configurations
profile: 'atl_analytics'  # Matches the profile in profiles.yml for BigQuery connection
require-dbt-version: '>=1.3.0'

# Directory configurations
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Target directory for compiled artifacts
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Default schema and dataset configurations
vars:
  # Define the production dataset
  prod_dataset: 'atl_analytics'
  # Define development dataset prefix (will append username dynamically in dbt Cloud)
  dev_dataset_prefix: 'dbt_'

# Model configurations by layer
models:
  atl_analytics:
    # Staging layer configuration
    staging:
      +materialized: view
      +schema: '{{ var("prod_dataset") if target.name == "prod" else var("dev_dataset_prefix") ~ target.user }}'
      +tags: ['staging']
      powerschool:
        +alias: 'stg_ps'
        +schema: '{{ var("prod_dataset") if target.name == "prod" else var("dev_dataset_prefix") ~ target.user }}_stg_ps'

    # Intermediate layer configuration
    core:
      intermediate:
        +materialized: view
        +schema: '{{ var("prod_dataset") if target.name == "prod" else var("dev_dataset_prefix") ~ target.user }}'
        +tags: ['intermediate']
        +alias: 'int_core'

      # Dimensional layer configuration (dim and fct tables)
      dimensional:
        +materialized: table
        +schema: '{{ var("prod_dataset") if target.name == "prod" else var("dev_dataset_prefix") ~ target.user }}'
        +tags: ['dimensional']
        dim:
          +alias: 'dim_core'
        fct:
          +alias: 'fct_core'

      # Datasource layer configuration
      datasource:
        +materialized: table
        +schema: '{{ var("prod_dataset") if target.name == "prod" else var("dev_dataset_prefix") ~ target.user }}'
        +tags: ['datasource']
        +alias: 'ds_core'

      # Reporting layer configuration
      reporting:
        +materialized: table
        +schema: '{{ var("prod_dataset") if target.name == "prod" else var("dev_dataset_prefix") ~ target.user }}'
        +tags: ['reporting']
        +alias: 'rpt_core'

# Source freshness configuration (example for monitoring staging sources)
# sources:
  # atl_analytics:
  #   staging:
  #     powerschool:
  #       +database: 'kae-cloud-kippatl'
  #       +schema: 'prod_staging'
  #       +freshness:
  #         warn_after: {count: 12, period: hour}
  #         error_after: {count: 24, period: hour}
  #       +loaded_at_field: '_file_last_modified'

# Testing configurations
tests:
  atl_analytics:
    staging:
      +severity: warn
      +store_failures: true
    core:
      intermediate:
        +severity: warn
      dimensional:
        +severity: error
      datasource:
        +severity: error
      reporting:
        +severity: error

# Documentation configurations
# docs:
#   paths: ["docs"]